wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.12
    start_time: 1644354179
    t:
      1:
      - 2
      - 3
      - 12
      3:
      - 16
      4: 3.7.12
      5: 0.12.10
      8:
      - 1
      - 5
architecture:
  desc: null
  value: yolo_v3
batch_size:
  desc: null
  value: 16
dataset:
  desc: null
  value: big
epochs:
  desc: null
  value: 5
